<?php get_header(); ?>

<main>
    <section class="hero">
        <div class="container hero-grid">
            <div>
                <?php if (function_exists('chess_podium_language_badges')) chess_podium_language_badges(); ?>
                <h1><?php chess_podium_te('Manage chess tournaments from WordPress in minutes.'); ?></h1>
                <p><?php chess_podium_te('Chess Podium helps clubs organize players, pair rounds, publish standings, share archives, and sell registrations from one place.'); ?></p>
                <?php $download_url = apply_filters('chess_podium_download_url', home_url('/download/')); ?>
                <a class="btn btn-primary" href="<?php echo esc_url($download_url); ?>"><?php chess_podium_te('Download free'); ?></a>
                <a class="btn" href="<?php echo esc_url(home_url('/pricing/')); ?>"><?php chess_podium_te('See pricing'); ?></a>
                <a class="btn" href="<?php echo esc_url(home_url('/features/')); ?>"><?php chess_podium_te('Explore features'); ?></a>
            </div>
            <div class="hero-visual card">
                <?php
                $hero_image = '';
                $hero_from_customizer = trim((string) get_theme_mod('chess_podium_hero_image', ''));
                $hero_png_path = get_template_directory() . '/assets/chess-podium-hero.png';
                $hero_webp_path = get_template_directory() . '/assets/chess-podium-hero.webp';

                if ($hero_from_customizer !== '') {
                    $hero_image = $hero_from_customizer;
                } elseif (file_exists($hero_png_path)) {
                    $hero_image = trailingslashit(get_template_directory_uri()) . 'assets/chess-podium-hero.png?v=' . filemtime($hero_png_path);
                } elseif (file_exists($hero_webp_path)) {
                    $hero_image = trailingslashit(get_template_directory_uri()) . 'assets/chess-podium-hero.webp?v=' . filemtime($hero_webp_path);
                }
                ?>
                <?php if ($hero_image !== '') : ?>
                    <img
                        src="<?php echo esc_url($hero_image); ?>"
                        alt="Chess Podium hero visual"
                        loading="eager"
                        fetchpriority="high"
                        decoding="async"
                        class="skip-lazy"
                    >
                <?php else : ?>
                    <h3><?php chess_podium_te('Built for real chess clubs'); ?></h3>
                    <p class="muted"><?php chess_podium_te('Swiss pairing, printable pairings, public standings, tournament archive, and a clear upgrade path to Pro.'); ?></p>
                    <ul>
                        <li><?php chess_podium_te('Fast setup before round 1'); ?></li>
                        <li><?php chess_podium_te('Works on standard WordPress hosting'); ?></li>
                        <li><?php chess_podium_te('Free plan for social tournaments'); ?></li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <h2><?php chess_podium_te('See it in action'); ?></h2>
            <p class="muted" style="margin-bottom:1.5rem;"><?php chess_podium_te('This is how a published tournament looks on your site: standings, rounds, pairings, games, and gallery—all generated by Chess Podium.'); ?></p>
            <div class="card" style="padding:1.5rem;">
                <h3 style="margin-top:0;"><?php chess_podium_te('Oxford University Chess Tournament'); ?></h3>
                <p class="muted"><?php chess_podium_te('Live example: 32 players, 9 rounds, Swiss pairing. Click to explore the full standings, round pairings, PGN games, and photo gallery.'); ?></p>
                <a class="btn btn-primary" href="https://www.chesspodium.com/wp-content/uploads/chess-podium/oxford-university-chess-tournament/" target="_blank" rel="noopener noreferrer">
                    <?php chess_podium_te('View live tournament page'); ?> →
                </a>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <h2><?php chess_podium_te('Why Chess Podium'); ?></h2>
            <div class="grid-3">
                <article class="card">
                    <h3><?php chess_podium_te('Save time'); ?></h3>
                    <p class="muted"><?php chess_podium_te('Create rounds, enter results, and update rankings without spreadsheets.'); ?></p>
                </article>
                <article class="card">
                    <h3><?php chess_podium_te('Publish instantly'); ?></h3>
                    <p class="muted"><?php chess_podium_te('Display current standings and tournament history directly on your site.'); ?></p>
                </article>
                <article class="card">
                    <h3><?php chess_podium_te('Monetize events'); ?></h3>
                    <p class="muted"><?php chess_podium_te('Pro only: online registration with Stripe and PayPal. Players pay the fee and are added automatically—perfect for clubs that want to cover costs.'); ?></p>
                </article>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <h2><?php chess_podium_te('Free vs Pro at a glance'); ?></h2>
            <div class="pricing">
                <div class="card">
                    <h3><?php chess_podium_te('Free'); ?></h3>
                    <p class="price">€0</p>
                    <p><?php chess_podium_te('Perfect for social tournaments and small clubs.'); ?></p>
                </div>
                <div class="card">
                    <h3><?php chess_podium_te('Pro Club'); ?></h3>
                    <p class="price">€79/<?php chess_podium_te('year'); ?></p>
                    <p><?php chess_podium_te('Online registration with Stripe & PayPal to monetize tournaments, unlimited players, exports, PGN, and branding.'); ?></p>
                </div>
            </div>
        </div>
    </section>
</main>

<?php get_footer(); ?>
